<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Biblio;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Bibliography extends \Pladias\ORM\Entity\Biblio\Bibliography implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'authors' => [parent::class, 'authors', null, 8196],
        'etc' => [parent::class, 'etc', null, 8196],
        'excerpted' => [parent::class, 'excerpted', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'journal' => [parent::class, 'journal', null, 8196],
        'journal_id' => [parent::class, 'journal_id', null, 8196],
        'original_id' => [parent::class, 'original_id', null, 8196],
        'original_string' => [parent::class, 'original_string', null, 8196],
        'remarks' => [parent::class, 'remarks', null, 8196],
        'title' => [parent::class, 'title', null, 8196],
        'year' => [parent::class, 'year', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
