<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Geodata;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Districts extends \Pladias\ORM\Entity\Geodata\Districts implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'abbrev' => [parent::class, 'abbrev', null, 8196],
        'color' => [parent::class, 'color', null, 8196],
        'depth' => [parent::class, 'depth', null, 8196],
        'geom_wgs' => [parent::class, 'geom_wgs', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'identificator' => [parent::class, 'identificator', null, 8196],
        'lft' => [parent::class, 'lft', null, 8196],
        'name' => [parent::class, 'name', null, 8196],
        'rank' => [parent::class, 'rank', null, 8196],
        'rgt' => [parent::class, 'rgt', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
