<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Public;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Users extends \Pladias\ORM\Entity\Public\Users implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'biblioadmin' => [parent::class, 'biblioadmin', null, 8196],
        'deleted' => [parent::class, 'deleted', null, 8196],
        'description' => [parent::class, 'description', null, 8196],
        'email' => [parent::class, 'email', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'last_taxon_id' => [parent::class, 'last_taxon_id', null, 8196],
        'mapadmin' => [parent::class, 'mapadmin', null, 8196],
        'name' => [parent::class, 'name', null, 8196],
        'password' => [parent::class, 'password', null, 8196],
        'surname' => [parent::class, 'surname', null, 8196],
        'sysadmin' => [parent::class, 'sysadmin', null, 8196],
        'taxonadmin' => [parent::class, 'taxonadmin', null, 8196],
        'traitadmin' => [parent::class, 'traitadmin', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
