<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Bayernflora;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FSGTaxons extends \Pladias\ORM\Entity\Bayernflora\FSGTaxons implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'altitudeMax' => [parent::class, 'altitudeMax', null, 8196],
        'altitudeMin' => [parent::class, 'altitudeMin', null, 8196],
        'bayernTaxa' => [parent::class, 'bayernTaxa', null, 8196],
        'descriptionCz' => [parent::class, 'descriptionCz', null, 8196],
        'descriptionDe' => [parent::class, 'descriptionDe', null, 8196],
        'descriptionEn' => [parent::class, 'descriptionEn', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'images' => [parent::class, 'images', null, 8196],
        'isFsg' => [parent::class, 'isFsg', null, 8196],
        'isFvd' => [parent::class, 'isFvd', null, 8196],
        'nameCz' => [parent::class, 'nameCz', null, 8196],
        'nameDe' => [parent::class, 'nameDe', null, 8196],
        'nameLat' => [parent::class, 'nameLat', null, 8196],
        'pladiasTaxa' => [parent::class, 'pladiasTaxa', null, 8196],
        'redListCategory' => [parent::class, 'redListCategory', null, 8196],
        'redlistReason' => [parent::class, 'redlistReason', null, 8196],
        'taxonConvertor' => [parent::class, 'taxonConvertor', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
