<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Public;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TaxonRanks extends \Pladias\ORM\Entity\Public\TaxonRanks implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'abbreviationEng' => [parent::class, 'abbreviationEng', null, 8196],
        'category' => [parent::class, 'category', null, 8196],
        'icn' => [parent::class, 'icn', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'idDanihelka' => [parent::class, 'idDanihelka', null, 8196],
        'id_tv3' => [parent::class, 'id_tv3', null, 8196],
        'nameCz' => [parent::class, 'nameCz', null, 8196],
        'nameEng' => [parent::class, 'nameEng', null, 8196],
        'nameSuffix' => [parent::class, 'nameSuffix', null, 8196],
        'succession' => [parent::class, 'succession', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
