<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Atlas;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Herbariums extends \Pladias\ORM\Entity\Atlas\Herbariums implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'abbrev' => [parent::class, 'abbrev', null, 8196],
        'abbrev_explanation' => [parent::class, 'abbrev_explanation', null, 8196],
        'address' => [parent::class, 'address', null, 8196],
        'city' => [parent::class, 'city', null, 8196],
        'contact' => [parent::class, 'contact', null, 8196],
        'curator' => [parent::class, 'curator', null, 8196],
        'description' => [parent::class, 'description', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'import_id' => [parent::class, 'import_id', null, 8196],
        'name' => [parent::class, 'name', null, 8196],
        'owner' => [parent::class, 'owner', null, 8196],
        'validated' => [parent::class, 'validated', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
