<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Dalibcz;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Barcode extends \Pladias\ORM\Entity\Dalibcz\Barcode implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'accessionITS' => [parent::class, 'accessionITS', null, 8196],
        'accessionMTSSU' => [parent::class, 'accessionMTSSU', null, 8196],
        'country' => [parent::class, 'country', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'itemId' => [parent::class, 'itemId', null, 8196],
        'methodITS' => [parent::class, 'methodITS', null, 8196],
        'methodMTSSU' => [parent::class, 'methodMTSSU', null, 8196],
        'seqITS' => [parent::class, 'seqITS', null, 8196],
        'seqMTSSU' => [parent::class, 'seqMTSSU', null, 8196],
        'source' => [parent::class, 'source', null, 8196],
        'taxon' => [parent::class, 'taxon', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
