<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Bayernflora;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Dictionary extends \Pladias\ORM\Entity\Bayernflora\Dictionary implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'descriptionCs' => [parent::class, 'descriptionCs', null, 8196],
        'descriptionDe' => [parent::class, 'descriptionDe', null, 8196],
        'descriptionEn' => [parent::class, 'descriptionEn', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'nameCs' => [parent::class, 'nameCs', null, 8196],
        'nameDe' => [parent::class, 'nameDe', null, 8196],
        'nameEn' => [parent::class, 'nameEn', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
