<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Floravegeu;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Habitats extends \Pladias\ORM\Entity\Floravegeu\Habitats implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'code' => [parent::class, 'code', null, 8196],
        'depth' => [parent::class, 'depth', null, 8196],
        'description' => [parent::class, 'description', null, 8196],
        'hasMap' => [parent::class, 'hasMap', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'lft' => [parent::class, 'lft', null, 8196],
        'name' => [parent::class, 'name', null, 8196],
        'nameHTML' => [parent::class, 'nameHTML', null, 8196],
        'rank' => [parent::class, 'rank', null, 8196],
        'redListCode' => [parent::class, 'redListCode', null, 8196],
        'redListName' => [parent::class, 'redListName', null, 8196],
        'rgt' => [parent::class, 'rgt', null, 8196],
        'syntaxa_relationships' => [parent::class, 'syntaxa_relationships', null, 8196],
        'syntaxa_relationships_nonvascular' => [parent::class, 'syntaxa_relationships_nonvascular', null, 8196],
        'taxaNonvascular' => [parent::class, 'taxaNonvascular', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
