<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Atlas;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Comments extends \Pladias\ORM\Entity\Atlas\Comments implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'author' => [parent::class, 'author', null, 8196],
        'creation_timestamp' => [parent::class, 'creation_timestamp', null, 8196],
        'deleted' => [parent::class, 'deleted', null, 8196],
        'edit_timestamp' => [parent::class, 'edit_timestamp', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'imported' => [parent::class, 'imported', null, 8196],
        'message' => [parent::class, 'message', null, 8196],
        'record' => [parent::class, 'record', null, 8196],
        'resolved' => [parent::class, 'resolved', null, 8196],
        'resolved_timestamp' => [parent::class, 'resolved_timestamp', null, 8196],
        'solver' => [parent::class, 'solver', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
