<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Public;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Syntaxons extends \Pladias\ORM\Entity\Public\Syntaxons implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'author' => [parent::class, 'author', null, 8196],
        'author_2' => [parent::class, 'author_2', null, 8196],
        'author_html' => [parent::class, 'author_html', null, 8196],
        'bibliography' => [parent::class, 'bibliography', null, 8196],
        'citationHTML' => [parent::class, 'citationHTML', null, 8196],
        'code' => [parent::class, 'code', null, 8196],
        'comment' => [parent::class, 'comment', null, 8196],
        'depth' => [parent::class, 'depth', null, 8196],
        'description' => [parent::class, 'description', null, 8196],
        'diagnosticNonvascular' => [parent::class, 'diagnosticNonvascular', null, 8196],
        'filename' => [parent::class, 'filename', null, 8196],
        'habitat_relationships' => [parent::class, 'habitat_relationships', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'images' => [parent::class, 'images', null, 8196],
        'lft' => [parent::class, 'lft', null, 8196],
        'map_filename' => [parent::class, 'map_filename', null, 8196],
        'nameCs' => [parent::class, 'nameCs', null, 8196],
        'nameEn' => [parent::class, 'nameEn', null, 8196],
        'name_cz_html' => [parent::class, 'name_cz_html', null, 8196],
        'name_en_html' => [parent::class, 'name_en_html', null, 8196],
        'name_lat' => [parent::class, 'name_lat', null, 8196],
        'nomen' => [parent::class, 'nomen', null, 8196],
        'pages' => [parent::class, 'pages', null, 8196],
        'rank' => [parent::class, 'rank', null, 8196],
        'releveCount' => [parent::class, 'releveCount', null, 8196],
        'remarks' => [parent::class, 'remarks', null, 8196],
        'rgt' => [parent::class, 'rgt', null, 8196],
        'species_const_html' => [parent::class, 'species_const_html', null, 8196],
        'species_diag_html' => [parent::class, 'species_diag_html', null, 8196],
        'species_dominant_html' => [parent::class, 'species_dominant_html', null, 8196],
        'species_formal_html_cs' => [parent::class, 'species_formal_html_cs', null, 8196],
        'species_formal_html_en' => [parent::class, 'species_formal_html_en', null, 8196],
        'synonyms' => [parent::class, 'synonyms', null, 8196],
        'synonymum_html' => [parent::class, 'synonymum_html', null, 8196],
        'syntaxons_sections' => [parent::class, 'syntaxons_sections', null, 8196],
        'text_1' => [parent::class, 'text_1', null, 8196],
        'text_2' => [parent::class, 'text_2', null, 8196],
        'text_3' => [parent::class, 'text_3', null, 8196],
        'text_en' => [parent::class, 'text_en', null, 8196],
        'vegkeyForest' => [parent::class, 'vegkeyForest', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
