<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Public;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Taxons extends \Pladias\ORM\Entity\Public\Taxons implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'author' => [parent::class, 'author', null, 8196],
        'comment' => [parent::class, 'comment', null, 8196],
        'depth' => [parent::class, 'depth', null, 8196],
        'depthBackup' => [parent::class, 'depthBackup', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'idDanihelka' => [parent::class, 'idDanihelka', null, 8196],
        'lft' => [parent::class, 'lft', null, 8196],
        'lft_backup' => [parent::class, 'lft_backup', null, 8196],
        'nameCz' => [parent::class, 'nameCz', null, 8196],
        'nameHtml' => [parent::class, 'nameHtml', null, 8196],
        'nameLatin' => [parent::class, 'nameLatin', null, 8196],
        'parents' => [parent::class, 'parents', null, 8196],
        'parentsCz' => [parent::class, 'parentsCz', null, 8196],
        'protected' => [parent::class, 'protected', null, 8196],
        'rank' => [parent::class, 'rank', null, 8196],
        'rgt' => [parent::class, 'rgt', null, 8196],
        'rgt_backup' => [parent::class, 'rgt_backup', null, 8196],
        'suppressed' => [parent::class, 'suppressed', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
