<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Floravegeu;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TaxonsImages extends \Pladias\ORM\Entity\Floravegeu\TaxonsImages implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'altitude' => [parent::class, 'altitude', null, 8196],
        'author' => [parent::class, 'author', null, 8196],
        'country' => [parent::class, 'country', null, 8196],
        'date' => [parent::class, 'date', null, 8196],
        'datePrecision' => [parent::class, 'datePrecision', null, 8196],
        'external_id' => [parent::class, 'external_id', null, 8196],
        'filename' => [parent::class, 'filename', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'locality' => [parent::class, 'locality', null, 8196],
        'remark' => [parent::class, 'remark', null, 8196],
        'representative' => [parent::class, 'representative', null, 8196],
        'source' => [parent::class, 'source', null, 8196],
        'succession' => [parent::class, 'succession', null, 8196],
        'taxon' => [parent::class, 'taxon', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
