<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Public;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Publications extends \Pladias\ORM\Entity\Public\Publications implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'abbrev' => [parent::class, 'abbrev', null, 8196],
        'authors' => [parent::class, 'authors', null, 8196],
        'autocomplete' => [parent::class, 'autocomplete', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'publisher' => [parent::class, 'publisher', null, 8196],
        'succession' => [parent::class, 'succession', null, 8196],
        'textCz' => [parent::class, 'textCz', null, 8196],
        'textEn' => [parent::class, 'textEn', null, 8196],
        'title' => [parent::class, 'title', null, 8196],
        'year' => [parent::class, 'year', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
