<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Dalibcz;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TaxonInfo extends \Pladias\ORM\Entity\Dalibcz\TaxonInfo implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'taxon' => [parent::class, 'taxon', null, 8],
        'descriptionCs' => [parent::class, 'descriptionCs', null, 8196],
        'descriptionEn' => [parent::class, 'descriptionEn', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'taxon' => [parent::class, 'taxon', null, 8],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
