<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Measurements;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Traits extends \Pladias\ORM\Entity\Measurements\Traits implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'attachment' => [parent::class, 'attachment', null, 8196],
        'attachment_type' => [parent::class, 'attachment_type', null, 8196],
        'creationTimestamp' => [parent::class, 'creationTimestamp', null, 8196],
        'default_values' => [parent::class, 'default_values', null, 8196],
        'deleted' => [parent::class, 'deleted', null, 8196],
        'descriptionCs' => [parent::class, 'descriptionCs', null, 8196],
        'descriptionEn' => [parent::class, 'descriptionEn', null, 8196],
        'feature_id' => [parent::class, 'feature_id', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'owner' => [parent::class, 'owner', null, 8196],
        'sourceCs' => [parent::class, 'sourceCs', null, 8196],
        'sourceEn' => [parent::class, 'sourceEn', null, 8196],
        'visibility_status_id' => [parent::class, 'visibility_status_id', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
