<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Public;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TaxonSynonyms extends \Pladias\ORM\Entity\Public\TaxonSynonyms implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'autocomplete' => [parent::class, 'autocomplete', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'nameHtml' => [parent::class, 'nameHtml', null, 8196],
        'nameLat' => [parent::class, 'nameLat', null, 8196],
        'publication' => [parent::class, 'publication', null, 8196],
        'suffix' => [parent::class, 'suffix', null, 8196],
        'taxon' => [parent::class, 'taxon', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
