<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Bayernflora;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BayernTaxons extends \Pladias\ORM\Entity\Bayernflora\BayernTaxons implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'convertor' => [parent::class, 'convertor', null, 8196],
        'foreignId' => [parent::class, 'foreignId', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'nameLat' => [parent::class, 'nameLat', null, 8196],
        'nameLatFull' => [parent::class, 'nameLatFull', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
