<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Gbif;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Taxa extends \Pladias\ORM\Entity\Gbif\Taxa implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'acceptedScientificName' => [parent::class, 'acceptedScientificName', null, 8196],
        'acceptedTaxonKey' => [parent::class, 'acceptedTaxonKey', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'pladiasTaxon' => [parent::class, 'pladiasTaxon', null, 8196],
        'scientificName' => [parent::class, 'scientificName', null, 8196],
        'species' => [parent::class, 'species', null, 8196],
        'speciesKey' => [parent::class, 'speciesKey', null, 8196],
        'taxonKey' => [parent::class, 'taxonKey', null, 8196],
        'taxonRank' => [parent::class, 'taxonRank', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
