<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Atlas;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TaxonMapsettings extends \Pladias\ORM\Entity\Atlas\TaxonMapsettings implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'PresliaReportLink' => [parent::class, 'PresliaReportLink', null, 8196],
        'common_threshold' => [parent::class, 'common_threshold', null, 8196],
        'edit_count' => [parent::class, 'edit_count', null, 8196],
        'edit_timestamp' => [parent::class, 'edit_timestamp', null, 8196],
        'is_mapped' => [parent::class, 'is_mapped', null, 8196],
        'locked' => [parent::class, 'locked', null, 8196],
        'map_type' => [parent::class, 'map_type', null, 8196],
        'mapadmin_comment' => [parent::class, 'mapadmin_comment', null, 8196],
        'preslia' => [parent::class, 'preslia', null, 8196],
        'publication_status' => [parent::class, 'publication_status', null, 8196],
        'revision_status' => [parent::class, 'revision_status', null, 8196],
        'revisors_comment' => [parent::class, 'revisors_comment', null, 8196],
        'superior_taxon' => [parent::class, 'superior_taxon', null, 8196],
        'taxon_id' => [parent::class, 'taxon_id', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
