<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Floravegeu;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SyntaxonsRemarksVersions extends \Pladias\ORM\Entity\Floravegeu\SyntaxonsRemarksVersions implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'content' => [parent::class, 'content', null, 8196],
        'createdAt' => [parent::class, 'createdAt', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'prefix' => [parent::class, 'prefix', null, 8196],
        'syntaxon' => [parent::class, 'syntaxon', null, 8196],
        'versionDescription' => [parent::class, 'versionDescription', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
