<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Pladiascz;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DownloadsFiles extends \Pladias\ORM\Entity\Pladiascz\DownloadsFiles implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'buttonCs' => [parent::class, 'buttonCs', null, 8196],
        'buttonEn' => [parent::class, 'buttonEn', null, 8196],
        'downloadsId' => [parent::class, 'downloadsId', null, 8196],
        'fileCs' => [parent::class, 'fileCs', null, 8196],
        'fileEn' => [parent::class, 'fileEn', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'succession' => [parent::class, 'succession', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
