<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Dalibcz;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Images extends \Pladias\ORM\Entity\Dalibcz\Images implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'author' => [parent::class, 'author', null, 8196],
        'description' => [parent::class, 'description', null, 8196],
        'fileExtension' => [parent::class, 'fileExtension', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'mimeType' => [parent::class, 'mimeType', null, 8196],
        'sizeRaw' => [parent::class, 'sizeRaw', null, 8196],
        'taxon' => [parent::class, 'taxon', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
