<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Atlas;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Records extends \Pladias\ORM\Entity\Atlas\Records implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'altitude_approx' => [parent::class, 'altitude_approx', null, 8196],
        'altitude_max' => [parent::class, 'altitude_max', null, 8196],
        'altitude_min' => [parent::class, 'altitude_min', null, 8196],
        'authors' => [parent::class, 'authors', null, 8196],
        'batch_id' => [parent::class, 'batch_id', null, 8196],
        'comment' => [parent::class, 'comment', null, 8196],
        'coords_wgs' => [parent::class, 'coords_wgs', null, 8196],
        'datum' => [parent::class, 'datum', null, 8196],
        'datum_precision' => [parent::class, 'datum_precision', null, 8196],
        'detrev' => [parent::class, 'detrev', null, 8196],
        'district' => [parent::class, 'district', null, 8196],
        'edit_timestamp' => [parent::class, 'edit_timestamp', null, 8196],
        'environment' => [parent::class, 'environment', null, 8196],
        'gps_coords_precision' => [parent::class, 'gps_coords_precision', null, 8196],
        'gps_coords_source' => [parent::class, 'gps_coords_source', null, 8196],
        'herbariumQuality' => [parent::class, 'herbariumQuality', null, 8196],
        'herbariums' => [parent::class, 'herbariums', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'includeInMap' => [parent::class, 'includeInMap', null, 8196],
        'latitude' => [parent::class, 'latitude', null, 8196],
        'locality' => [parent::class, 'locality', null, 8196],
        'longitude' => [parent::class, 'longitude', null, 8196],
        'nearestTown' => [parent::class, 'nearestTown', null, 8196],
        'nearest_town_text' => [parent::class, 'nearest_town_text', null, 8196],
        'nonVascularExtension' => [parent::class, 'nonVascularExtension', null, 8196],
        'original_name' => [parent::class, 'original_name', null, 8196],
        'originalityStatus' => [parent::class, 'originalityStatus', null, 8196],
        'phytochorion' => [parent::class, 'phytochorion', null, 8196],
        'project' => [parent::class, 'project', null, 8196],
        'source' => [parent::class, 'source', null, 8196],
        'taxon' => [parent::class, 'taxon', null, 8196],
        'validationStatus' => [parent::class, 'validationStatus', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
