<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Measurements;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Features extends \Pladias\ORM\Entity\Measurements\Features implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'administrator' => [parent::class, 'administrator', null, 8196],
        'bibliography_cs' => [parent::class, 'bibliography_cs', null, 8196],
        'bibliography_en' => [parent::class, 'bibliography_en', null, 8196],
        'datatype_id' => [parent::class, 'datatype_id', null, 8196],
        'descriptionCs' => [parent::class, 'descriptionCs', null, 8196],
        'descriptionEn' => [parent::class, 'descriptionEn', null, 8196],
        'determinationUnionInsteadIntersect' => [parent::class, 'determinationUnionInsteadIntersect', null, 8196],
        'enumerate' => [parent::class, 'enumerate', null, 8196],
        'explanation_cs' => [parent::class, 'explanation_cs', null, 8196],
        'explanation_en' => [parent::class, 'explanation_en', null, 8196],
        'external_id' => [parent::class, 'external_id', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'inheritance' => [parent::class, 'inheritance', null, 8196],
        'maximum' => [parent::class, 'maximum', null, 8196],
        'minimum' => [parent::class, 'minimum', null, 8196],
        'nameCs' => [parent::class, 'nameCs', null, 8196],
        'nameEn' => [parent::class, 'nameEn', null, 8196],
        'precisionOnPublicWeb' => [parent::class, 'precisionOnPublicWeb', null, 8196],
        'section_id' => [parent::class, 'section_id', null, 8196],
        'show_description_on_public_web' => [parent::class, 'show_description_on_public_web', null, 8196],
        'show_on_public_web' => [parent::class, 'show_on_public_web', null, 8196],
        'succession' => [parent::class, 'succession', null, 8196],
        'syntaxon_restricted_rank_id' => [parent::class, 'syntaxon_restricted_rank_id', null, 8196],
        'traits' => [parent::class, 'traits', null, 8196],
        'unit' => [parent::class, 'unit', null, 8196],
        'useForDetermination' => [parent::class, 'useForDetermination', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
