<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Public;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Institutions extends \Pladias\ORM\Entity\Public\Institutions implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'id' => [parent::class, 'id', null, 8196],
        'name' => [parent::class, 'name', null, 8196],
        'name_eng' => [parent::class, 'name_eng', null, 8196],
        'name_short' => [parent::class, 'name_short', null, 8196],
        'users' => [parent::class, 'users', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
