<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Pladiascz;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class IndexHerbariorum extends \Pladias\ORM\Entity\Pladiascz\IndexHerbariorum implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'acronym' => [parent::class, 'acronym', null, 8196],
        'addressCorrespondence' => [parent::class, 'addressCorrespondence', null, 8196],
        'addressVisiting' => [parent::class, 'addressVisiting', null, 8196],
        'collections' => [parent::class, 'collections', null, 8196],
        'collectors' => [parent::class, 'collectors', null, 8196],
        'countDatabased' => [parent::class, 'countDatabased', null, 8196],
        'countOnline' => [parent::class, 'countOnline', null, 8196],
        'countPhotoprivate' => [parent::class, 'countPhotoprivate', null, 8196],
        'countPhotopublic' => [parent::class, 'countPhotopublic', null, 8196],
        'countTotal' => [parent::class, 'countTotal', null, 8196],
        'curatorLead' => [parent::class, 'curatorLead', null, 8196],
        'curatorOthers' => [parent::class, 'curatorOthers', null, 8196],
        'custods' => [parent::class, 'custods', null, 8196],
        'email' => [parent::class, 'email', null, 8196],
        'externalId' => [parent::class, 'externalId', null, 8196],
        'gbif' => [parent::class, 'gbif', null, 8196],
        'gpsVisiting' => [parent::class, 'gpsVisiting', null, 8196],
        'herbariumFounded' => [parent::class, 'herbariumFounded', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'institutionFounded' => [parent::class, 'institutionFounded', null, 8196],
        'institutionName' => [parent::class, 'institutionName', null, 8196],
        'note' => [parent::class, 'note', null, 8196],
        'phone' => [parent::class, 'phone', null, 8196],
        'pladiasHerbarium' => [parent::class, 'pladiasHerbarium', null, 8196],
        'provenience' => [parent::class, 'provenience', null, 8196],
        'response_2025' => [parent::class, 'response_2025', null, 8196],
        'surveyId' => [parent::class, 'surveyId', null, 8196],
        'webCatalogue' => [parent::class, 'webCatalogue', null, 8196],
        'webInstitution' => [parent::class, 'webInstitution', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
