<?php

namespace Nettrine\Proxy\__CG__\Pladias\ORM\Entity\Measurements;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Datatypes extends \Pladias\ORM\Entity\Measurements\Datatypes implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'descriptionCs' => [parent::class, 'descriptionCs', null, 8196],
        'descriptionEn' => [parent::class, 'descriptionEn', null, 8196],
        'dominantValue' => [parent::class, 'dominantValue', null, 8196],
        'frequency' => [parent::class, 'frequency', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'key' => [parent::class, 'key', null, 8196],
        'max' => [parent::class, 'max', null, 8196],
        'min' => [parent::class, 'min', null, 8196],
        'multiplicity' => [parent::class, 'multiplicity', null, 8196],
        'nameCs' => [parent::class, 'nameCs', null, 8196],
        'tablename' => [parent::class, 'tablename', null, 8196],
        'unmeasurable' => [parent::class, 'unmeasurable', null, 8196],
        'valueComment' => [parent::class, 'valueComment', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
