name: Tests

on:
    push:
        branches:
            - test
    workflow_dispatch:  # Manual run
jobs:
    test:
        name: Run tests and collect coverage
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            #install PHP dependencies
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.4'
                    tools: composer:v2
                    extensions: mbstring, json

            -   name: Get composer cache directory
                id: composer-cache
                working-directory: ./htdocs
                run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            -   name: Cache composer dependencies
                uses: actions/cache@v4.2.0
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-

            -   name: Install Composer dependencies
                working-directory: ./htdocs
                run: composer install --no-progress --prefer-dist --optimize-autoloader

            -   name: Create config file
                working-directory: ./htdocs
                run: cp ./config/local.neon.template ./config/local.neon

            -   name: Run tests
                working-directory: ./htdocs
                run: vendor/bin/tester -p phpdbg tests -s -C --coverage ./coverage.xml --coverage-src App

            -   name: Upload results to Codecov
                uses: codecov/codecov-action@v5
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    files: coverage.xml
                    fail_ci_if_error: false
